# Introduction Jupyter/ Python/ OpenCV/ Numpy
**Objectives of the lesson:**

1. Introduction Basics Python
2. Introduction Basics Vector/ Matrix Calculation
3. Introduction Basics Image Processing

## Introduction Jupyter Notebook

**Shortcuts:**
- SHIFT + ENTER (execute cell)
- Double tap D (delete blue marked cell)
- Up & Down (navigate through notebook)

## 1. Introduction Basics Python

In [1]:
# Check Python Version installed on Machine (e.g. Server or Laptop)
!python --version

Python 3.8.8


In [2]:
# System output inside cmd 
print("WS 21/22")

WS 21/22


In [3]:
# Mathematical operations - no explicit type specification necessary
i = 1
f = 1.0
b = True
s = "BiVe/ CoVis 21/22"

#Check datatype of variables
print(isinstance(i, int))
print(isinstance(f, float))
print(isinstance(b, bool))
print(isinstance(s, str))

True
True
True
True


In [4]:
#define array 
int_array = [(1,1), (2,2)]

#print array
print(int_array)

#for-loop - iterate through array a
for i in int_array:
    print("Sub-container: " + str(i))

#if statement - check if int_array has value assigned
if(int_array != None):
    print("Array has valued asigned")

[(1, 1), (2, 2)]
Sub-container: (1, 1)
Sub-container: (2, 2)
Array has valued asigned


In [5]:
# define a function - returns info about lecture as string
def lecture_info(i):
    return "This lecture is called " + i + " WS 21/22"  

In [6]:
name = "Computer Vision"
# call function lecture_info
print(lecture_info(name))

This lecture is called Computer Vision WS 21/22


## 2. Introduction Basics Vector/ Matrix Calculation

In [7]:
#import numpy library to get useful & efficent calculation tools
import numpy 

### 2.1 Vectors

In [8]:
#create vector with numpy - horizontal orientation
vec_h = numpy.array([1, 2, 3])

#create vector with numpy - vertical orientation
vec_v = numpy.array([[1], [2], [3]])

#print vectors horizontal
print("\nHorizontal: \n" + str(vec_h))

#print vector vertical
print("\nVertical: \n" + str(vec_v))

#transpose vector
print("\nTranspose vertical vector:\n" + str(vec_v.transpose()))

#vector calculations
print("\nVector calculation addition: \n" + str(vec_h + 3))
print("\nVector calculation subtraction: \n" + str(vec_h - 3))
print("\nVector calculation multiplication: \n" + str(vec_h * 3))
print("\nVector calculation division: \n" + str(vec_h / 3))

#calculate dot product
vec_d = numpy.array([3, 2, 1])
print("\nDot product: \n" + str(numpy.dot(vec_d, vec_h)))


Horizontal: 
[1 2 3]

Vertical: 
[[1]
 [2]
 [3]]

Transpose vertical vector:
[[1 2 3]]

Vector calculation addition: 
[4 5 6]

Vector calculation subtraction: 
[-2 -1  0]

Vector calculation multiplication: 
[3 6 9]

Vector calculation division: 
[0.33333333 0.66666667 1.        ]

Dot product: 
10


### 2.2 Vector Exercises

**Exercise 2.2.1: Implement the function even_odd(vector_50)  to check whether a vector of N:1-50 numbers contains more even or odd values. Return your result as string. (Difficulty 1)**

In [9]:
def even_odd(vector_50):
    counterUng = 0
    counterGer = 0
    
    for i in vector_50:
        if(i % 2 != 0):
            counterUng+=1
        else:
            counterGer+=1
    
    if(counterGer > counterUng):
        return str("Gerade: " + str(counterGer))
    else:
        return str("Ungerade: " + str(counterUng))

    #return "Return !"

In [10]:
#Create random vector with 50 integer values in the range between 1 to 50
vector_50 = numpy.random.randint(1,50, size=(50,1))
#Call function from exercise 2.1.1 to check the results
print(even_odd(vector_50))

Ungerade: 26


### 2.3 Matrices

In [11]:
#create matrices with numpy
mat_zeros = numpy.zeros((3,2), dtype=int)
mat_ones = numpy.ones((3,3), dtype=float)
mat_rand = numpy.random.rand(3, 3)
mat_rand_int = numpy.random.randint(1, 10, size=(5,5))

print("\nZeros Matrix:\n" + str(mat_zeros))
print("\nOnes Matrix:\n" + str(mat_ones)) 
print("\nRandom Matrix:\n" + str(mat_rand))

#matrix calculations
print("\nMatrix 3x3 addition:\n" + str(mat_ones + mat_rand))
print("\nMatrix 3x3 subtraction:\n" + str(mat_ones - mat_rand))
print("\nMatrix 3x3 division:\n" + str(mat_ones / mat_rand))
print("\nMatrix 3x3 multiplication:\n" + str(mat_ones * mat_rand))

#access matrices
print("\nAccess all rows from mat_zeros: \n" + str(mat_zeros[0:]))
print("\nAccess specific rows from mat_zeros: \n" + str(mat_zeros[0:2]))
print("\nAccess specific columns from mat_zeros: \n" + str(mat_zeros[0:,[0,1]]))
print("\nAccess last element from mat_rand: \n" + str(mat_rand[2][2]))
print("\nAccess shape attribute from mat_zeros: \n" + str(mat_zeros.shape))

#matrix operations
print("\nCalculate determinant of mat_ones:\n" + str(numpy.linalg.det(mat_ones)))
print("\nCalculate inverse of mat_rand:\n" + str(numpy.linalg.inv(mat_rand)))
print("\nCalculte rank of matrix mat_rand_int:\n" + str(numpy.linalg.matrix_rank(mat_rand_int)))


Zeros Matrix:
[[0 0]
 [0 0]
 [0 0]]

Ones Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Random Matrix:
[[0.12214314 0.35374741 0.82315972]
 [0.60428092 0.50652228 0.73880602]
 [0.44068621 0.2640901  0.26091058]]

Matrix 3x3 addition:
[[1.12214314 1.35374741 1.82315972]
 [1.60428092 1.50652228 1.73880602]
 [1.44068621 1.2640901  1.26091058]]

Matrix 3x3 subtraction:
[[0.87785686 0.64625259 0.17684028]
 [0.39571908 0.49347772 0.26119398]
 [0.55931379 0.7359099  0.73908942]]

Matrix 3x3 division:
[[8.18711536 2.82687583 1.21483106]
 [1.65485947 1.97424682 1.35353527]
 [2.26918834 3.78658641 3.83273073]]

Matrix 3x3 multiplication:
[[0.12214314 0.35374741 0.82315972]
 [0.60428092 0.50652228 0.73880602]
 [0.44068621 0.2640901  0.26091058]]

Access all rows from mat_zeros: 
[[0 0]
 [0 0]
 [0 0]]

Access specific rows from mat_zeros: 
[[0 0]
 [0 0]]

Access specific columns from mat_zeros: 
[[0 0]
 [0 0]
 [0 0]]

Access last element from mat_rand: 
0.26091058087237584

Access shape attribute

### 2.4 Matrix exercises

**Exercise 2.4.1: Implement the function mat_det(mat) to calculate the determinat of a 2x2 Matrix. Return your result as integer value. Don't use numpy for this. (Difficulty 1)**

In [12]:
def mat_det(mat):
    matrixberechnung = (mat[0,0] * mat[1,1]) - (mat[1,0] * mat[0,1])
    return "Matrixergebnis: " + str(abs(matrixberechnung))

In [13]:
#Create random matrix with integer values in the range between 1 to 50. Shape 2x2
mat_2x2 = numpy.random.randint(1, 50, (2,2))
#Call function from exercise 2.2.1 to check the results
print(mat_det(mat_2x2))

Matrixergebnis: 156


**Exercise 2.4.2: Implement the function calc_square_diag(mat) to add up the diagonal of a matrix leftwise. Return your result as integer value. (Difficulty 2)**

In [14]:
#e.g. leftwise_result = a + a + a

# a b b #
# b a b #
# b b a #

In [15]:
def calc_square_diag(mat):
    rang = numpy.linalg.matrix_rank(mat)
    rang -= 1
    counter = 0
    summe = 0
    
    while(counter != rang):
        summe+=mat[counter,counter]  
        counter+=1
       
    return summe

In [16]:
#Create random matrix with integer values in the range between 1 to 50. Shape 10x10
diag_mat_cal = numpy.random.randint(1,9, (10,10))
#Call function from exercise 2.2.2 to check the results
print(calc_square_diag(diag_mat_cal))

36


**Exercise 2.4.3: Implement the functions mirror_horizontal(mat) and mirror_vertical(mat) to mirror matrices around the specific axis. Each function should return the edited matrix. (Difficulty 3)**

In [17]:
# vertical:    a b c -> c b a

# horizontal:  a a a -> b b b
#              b b b    a a a

In [18]:
def mirror_vertical(mat):
    return mat

In [19]:
def mirror_horizontal(mat):
    return mat

In [20]:
#Create random matrix with integer values in the range between 1 to 10. Shape 2x2
mat_mir_h = numpy.random.randint(1,10, size=(2,2))
#Call function from exercise 2.2.3 to check the results
print(mirror_horizontal(mat_mir_h))

#Create random matrix with integer values in the range between 1 to 10. Shape 2x2
mat_mir_v = numpy.random.randint(1,10, size=(2,2))
#Call function from exercise 2.2.3 to check the results
print(mirror_vertical(mat_mir_v))

[[3 3]
 [2 3]]
[[6 6]
 [8 1]]


## 3. Introduction Basics Image Processing

In [21]:
#import pyplot & OpenCV libraries
import matplotlib.pyplot as plt
import cv2

ModuleNotFoundError: No module named 'cv2'

In [ ]:
#important: C:\Users\test\test\ComputerVision - on Windows change backslash to frontslash
#If the current image is in the same folder as Jupyter Notebook the image name should be enough to load the file correctly

#Here, we have an image from the repository, you can try using images stored locally.
img = cv2.imread('image1.jpg')

#show part of image container
print("Raw image values:\n" + str(img[0:1]))

print("\nGBR-image:")
plt.imshow(img)
plt.show()

#convert BGR color space to RGB color space image
print("\nRGB-image:")
rgb_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
plt.imshow(rgb_img)

#To save image locally
#plt.savefig("rbg_img_test")
#plt.show() is inside a Jupyter Notebook not required . imgplot = plt.imshow(img) will print the image correctly.
#instead using Python from CMD plt.show() is neccessary to print the image correctly
#also to seperate multiple images plt.show() is neccessary
plt.show()

### 3.2 Image Processing Exercises

**Exercise 3.2.1: Apply Canny filter to the pre-loaded image rgb_img from cell above between the range 100 to 200. Hint: use a OpenCV function for this.(Difficulty 1)**

In [ ]:
print("\nCanny filter:")
# Uncomment the following line after applying the canny filter.
# plt.imshow(image_edge_canny)

**Exercise 3.2.2: Apply greyscale filter to an loaded image. (Difficulty 3)**

In [ ]:
bgr_img = cv2.imread('image2.jpg')
plt.imshow(bgr_img)
plt.show()

print("\nGrey-image:")