## Exercise 03: Linear Optimization using Pseudo Inverse
**Objectives of the lesson:**

1. Create 2-D Datapoint & Linear Equation
2. Leftwise Moore-Penrose Pseudo-Inverse
3. Leftwise SVD Pseudo-Inverse + Student Exercise
4. Solve Linear Equation
5. Calculate Error Rate

In [8]:
#import Numpy for numerical operations, alias 'np' in code below
import numpy as np

## 1. Create 2-D Datapoint & Linear Equation 

**Linear Equation: y = a*x + b, 2-D datapoint di = (x,y)**

**Aim of cell below:** Bring given 2-D datapoints in form of linear equation, e.g. for three datapoints: <br>
[x1 1]$\;\;$  [a]$\;\;$     [y1]<br>
[x2 1] * [b]  = [y2]<br>
[x3 1]$\;\;$$\;\;$$\;\;$$\;\;$   [y3]

In [9]:
# Given 2-D datapoints, d1 = (2, 2.95), d2 = (6, 4.9), d3 = (4, 4.2)
data = np.matrix([[2, 2.95],
                  [6, 4.9],
                  [4, 4.2]])

# create linear equation 
x = np.ones(data.shape)

# y for 2-D datapoints, /2 -> Please change for 3-D : /3 
y = np.ones(int(data.size/2))

index_rows = 0

for i in data:
        # copy columns from data to equation variables
        x[index_rows][0] = i[:,0]
        y[index_rows] = i[:,1]
        # update row index
        index_rows = index_rows + 1

#final variables
print("\nslope-intercept-x-values: \n" + str(x))
print("\ny-values: \n" + str(y))


slope-intercept-x-values: 
[[2. 1.]
 [6. 1.]
 [4. 1.]]

y-values: 
[2.95 4.9  4.2 ]


## 2. Leftwise Moore-Penrose Pseudo-Inverse

**Matrix_Pseudo_Inverse = (((A^T) * A)^-1) * (A^T)**

A^T : Transposed Matrix A<br>
A^-1: Inverse of Matrix A

In [10]:
# function to calculate moore penrose inverse
def moore_penrose_inverse(matrix):
    matrix_inv = np.round(np.dot((np.linalg.inv(np.dot(np.transpose(matrix),matrix))), np.transpose(matrix)), 9)
    return matrix_inv

## 3. Leftwise SVD Pseudo-Inverse + Student Exercise

**A = U * Sigma * (V^T)**

A: Matrix 

**Matrix_Pseudo_Inverse = V * (Simga^+) * (U^T)**

U^T: Transposed U <br>
Sigma^+: Inverse of the diagonal of Sigma, (Sigma^x == ((Sigma^x)^T)


In [12]:
# function to calculate SVD
def svd(A):
    # if count rows < count columns, calculate Eigenvalues with AA^T and V first
    if len(A) < len(A[0]):
        # calculate Eigenvalues with AA^T
        AAT = A.dot(np.transpose(A))
        lamb, e = np.linalg.eig(AAT)
        # sort Eigenvalues descending
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # calculate Sigma 
        Sigma = np.zeros((len(A),len(A[0])))
        for i in range(len(A)):
            Sigma[i,i] = np.sqrt(lamb[i])
    
        # calculate Eigenvalues from A^TA
        ATA = np.transpose(A).dot(A)
        lamb, e = np.linalg.eig(ATA)
    
        # sort Eigenvalues descending
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # calculate V
        V = np.zeros((len(A[0]), len(A[0])))
        for i in range(len(A[0])):
            for j in range(len(A[0])):
                V[i][j] = e[i][j]
        
        # calculate U
        U = np.zeros((len(A), len(A)))
        for i in range(len(A)):
            U[:,i] = np.divide(A.dot(V[:,i]),Sigma[i][i])
            
    else:
        # calculate Eigenvalues from A^TA
        ATA = np.transpose(A).dot(A)
        lamb, e = np.linalg.eig(ATA)
        # Sort Eigenvalues descending
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # calculate Sigma
        Sigma = np.zeros((len(A),len(A[0])))
        for i in range(len(A[0])):
            Sigma[i,i] = np.sqrt(lamb[i])
    
        # calculate Eigenvalues from AA^T
        AAT = A.dot(np.transpose(A))
        lamb, e = np.linalg.eig(AAT)
    
        # sort Eigenvalues descending
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # calculate U
        U = np.zeros((len(A), len(A)))
        for i in range(len(A)):
            for j in range(len(A)):
                U[i][j] = e[i][j]
        
        # calculate V
        V = np.zeros((len(A[0]), len(A[0])))
        for i in range(len(A[0])):
            V[:,i] = np.divide(np.transpose(A).dot(U[:,i]),Sigma[i][i])
    
    # show SVD
    #print("U = ", U)
    #print("Sigma = ", Sigma)
    #print("V = ", V)
    #print("A = ", U.dot(Sigma.dot(np.transpose(V))))
    
    ################################# Student Exercise #################################
    # task: Expand the given function to calculate the pseudo-inverse of matrix A with U,V and Sigma
    # hint: check formulas above chapter 3 & round up to 7 decimal places
    
    pseudo_inv_svd = 0
    
    ####Start student work
    
    print("SVD Pseudo-Inverse: \n", pseudo_inv_svd)
    
    return pseudo_inv_svd

## 4. Solve Linear Equation

**E.g. for solving equation with 3 datapoints:** <br>
[a]$\;\;$ = ([x1, 1]) ^-1 $\;\;$ * $\;\;$ [y1] <br>
[b] $\;\;$ $\;$ ([x2, 1])$\;\;$ $\;\;$$\;\;$ $\;\;$$\;\;$  [y2] <br>
$\;\;$ $\;\;$ $\;\;$ ([x3, 1])$\;\;$ $\;\;$ $\;\;$ $\;\;$$\;$  [y3]

In [5]:
# calculate result from linear equation - a,b | a*x + b = y
x_inv = moore_penrose_inverse(x)
print("Moore-Penrose Pseudo-Inverse:\n", x_inv)
##### Student Exercise - see chapter three for task description #####
#x_inv = svd(x) - should run to same results as More-Penrose pseudo-inverse
#print("SVD Peusdo-Inverse:\n", x_inv)
# solve linear equation, in this case 2-D for a,b 
result = np.dot(x_inv, y)
print("Values for unknown variables:\n", result)

Moore-Penrose Pseudo-Inverse:
 [[-0.25        0.25        0.        ]
 [ 1.33333333 -0.66666667  0.33333333]]
Values for unknown variables:
 [0.4875     2.06666666]


## 5. Calculate Error Rate (Optional for: Noisy Datapoints)
**E.g. for computing error with 3 datapoints:**<br>
[r1] $\;\;$ [y1]$\;\;$[x1, 1]$\;\;$ $\;\;$[a]<br>
[r2] = [y2] - [x2, 1] *$\;\;$ [b]<br>
[r3] $\;\;$ [y3]$\;\;$[x3, 1]   

In [6]:
# calculate error values regarding linear equation results
error_vec = y - (np.dot(x, result))
# calculate absolute error
error_r = np.absolute(np.dot(error_vec, error_vec))
#print error results
print("Error Vector: \n",error_vec)
# error value = np.dot(error vector, error vector), inner product
print("Error Value: \n", error_r)

Error Vector: 
 [-0.09166666 -0.09166666  0.18333334]
Error Value: 
 0.05041666666666676
