<h2>Code-Beispiel: Singulärwertzerlegung berechnen</h2>
<font size="3" face="Verdana">
<p style="text-align:justify">Im folgenden befindet sich eine Implementierung der Singulärwertzerlegung. Im zweiten Code-Block kann die Eingabematrix geändert und die dazugehörige Singulärwertzerlegung berechnet werden.</p>
<p style="text-align:justify">Dazu muss jedoch zuerst auch in den ersten Block geklickt werden und dieser durch drücken der "Run" Taste in der Leiste oben ausgeführt werden.</p>
</font>

In [1]:
import numpy as np

# Funktion zur Berechnung der Singulärwertzerlegung
def Singulaerwertzerlegung(A):
    
    # wenn Anzahl der Reihen kleiner als Anzahl der Spalten, berechne Eigenwerte mit AA^T und zuerst V
    if len(A) < len(A[0]):
        # Eigenwerte von AA^T berechnen
        AAT = A.dot(np.transpose(A))
        lamb, e = np.linalg.eig(AAT)
        # Eigenwerte sortieren (absteigend)
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # Sigma erstellen
        Sigma = np.zeros((len(A),len(A[0])))
        for i in range(len(A)):
            Sigma[i,i] = np.sqrt(lamb[i])
    
    
        # Eigenwerte von A^TA berechnen
        ATA = np.transpose(A).dot(A)
        lamb, e = np.linalg.eig(ATA)
    
        # Eigenwerte sortieren (absteigend)
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # V erstellen
        V = np.zeros((len(A[0]), len(A[0])))
        for i in range(len(A[0])):
            for j in range(len(A[0])):
                V[i][j] = e[i][j]
        
        # Berechnen von U
        U = np.zeros((len(A), len(A)))
        for i in range(len(A)):
            U[:,i] = np.divide(A.dot(V[:,i]),Sigma[i][i])
            
    else:
        # Eigenwerte von A^TA berechnen
        ATA = np.transpose(A).dot(A)
        lamb, e = np.linalg.eig(ATA)
        # Eigenwerte sortieren (absteigend)
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # Sigma erstellen
        Sigma = np.zeros((len(A),len(A[0])))
        for i in range(len(A[0])):
            Sigma[i,i] = np.sqrt(lamb[i])
    
    
        # Eigenwerte von AA^T berechnen
        AAT = A.dot(np.transpose(A))
        lamb, e = np.linalg.eig(AAT)
    
        # Eigenwerte sortieren (absteigend)
        idx = lamb.argsort()[::-1]
        lamb = lamb[idx]
        e = e[:,idx]
    
        # U erstellen
        U = np.zeros((len(A), len(A)))
        for i in range(len(A)):
            for j in range(len(A)):
                U[i][j] = e[i][j]
        
        # Berechnen von V
        V = np.zeros((len(A[0]), len(A[0])))
        for i in range(len(A[0])):
            V[:,i] = np.divide(np.transpose(A).dot(U[:,i]),Sigma[i][i])
    
    # Singulärwertzerlegung anzeigen
    print("U = ", U)
    print("Sigma = ", Sigma)
    print("V = ", V)
    print("A = ", U.dot(Sigma.dot(np.transpose(V))))

<font size="3" face="Verdana">
<p style="text-align:justify">Die Eingabe-Matrix kann beliebig geändert werden. Zum Ausführen des Codes muss zunächst in das Feld mit dem Code geklickt werden und dann in der Leiste oben auf "Run".</p>

In [2]:
# Eingabe-Matrix, kann beliebig geändert werden
#A = np.array([[Zeile 1],
#    [Zeile 2]])

A = np.array([[2, 1, 5],
    [0, -2, 3], [2, 3, 4], [4, 3, 2]])

Singulaerwertzerlegung(A)

U =  [[-0.58526771 -0.37290509 -0.01377053 -0.71987073]
 [-0.16650093 -0.74568816  0.38965598  0.51419338]
 [-0.59003749  0.0904194  -0.6671508   0.44563426]
 [-0.53065516  0.54471579  0.6347349   0.13711823]]
Sigma =  [[8.94196943 0.         0.        ]
 [0.         4.3328427  0.        ]
 [0.         0.         1.50587413]
 [0.         0.         0.        ]]
V =  [[-0.50025121  0.37247874  0.78167021]
 [-0.40419998  0.69789674 -0.59123812]
 [-0.76574872 -0.61171867 -0.19856779]]
A =  [[ 2.00000000e+00  1.00000000e+00  5.00000000e+00]
 [-6.10622664e-16 -2.00000000e+00  3.00000000e+00]
 [ 2.00000000e+00  3.00000000e+00  4.00000000e+00]
 [ 4.00000000e+00  3.00000000e+00  2.00000000e+00]]
