# Exercise 02:  Power Iteration/ Rayleigh Quotient/ Hotelling Deflation
**Objectives of the lesson:**

1. Introduction Power Iteration
2. Introduction Rayleigh Quotient
3. Introduction Hotelling Deflation
4. Interaction between all three functions

In [6]:
#import numpy to get need mathematical tools, np is an alias to numpy
import numpy as np

## 1. Introduction Power Iteration
**Purpose: Calculate largest Eigenvector due to convergence.**<br>
**The Power Iteration Input:** b-th A Matrix form Ax=λx, number of iterations

<br>
 b_k1:<br><br>
        A dot b_k<br>
     --------------- <br>
     || A dot b_k ||<br>


In [7]:
def power_iteration(A, iterations):
    # b_k is random vector with row-size of A. This vector will converge against the largest Eigenvector of given data matrix
    b_k = np.ones(A.shape[1])
    
    # i is the actual iteration until convergence of the eigenvector is reached
    for i in range(iterations):
        # dividend of b_ki
        b_k1_dividend = np.dot(A, b_k) 

        # divisor of b_ki - for this implementation calculate norm not max 
        b_k1_divisor = np.linalg.norm(b_k1_dividend)

        # combine dividend and divisor to complete the power iteration function
        b_k = b_k1_dividend / b_k1_divisor

    return b_k

## 2. Introduction Rayleigh Quotient
**Purpose: Calculate Eigenvalue out of given Eigenvector from Power Iteration.** <br>

**Rayleigh Quotient Input:** b-th A Matrix form Ax=λx, b-th Eigenvector from Power Iteration

<br>
R(A, b):<br><br>
    b' dot A dot b<br>
    ----------------<br>
    b' dot b<br>


In [8]:
def rayleigh_quotient(A, b):
    # dividend of R(A, b)
    ray_dividend = np.dot(b.transpose(), np.dot(A,b))
    # divisor of R(A, b)
    ray_divisor = np.dot(b.transpose(),ray_dividend)
    
    return  ray_dividend / ray_divisor

In [9]:
# symmetric and diagonizable matrix
matrix = np.array([ [-1,  -3, -1, 2],
                    [-3,   5, 3,  3],
                    [-1,   3,  1, 1],
                    [2,   3,  1, 3]])


### 2.1 First iteration step without Hotelling Deflation
**Why is the Eigenvector above negative?: Ax=λx is equal to  A * (-1) * x= λ * (-1) * x**

In [10]:
# first power iteration call
eig_vec = power_iteration(matrix, 100)
# first rayleigh quotient call
eig_val = rayleigh_quotient(matrix, eig_vec)

#results
print("Eigenvalue:\n" + str(np.round(eig_val, 3)))
print("Eigenvector:\n" + str(np.round(eig_vec, 3)))

Eigenvalue:
[-4.988  1.252  2.578  2.418]
Eigenvector:
[-0.2    0.799  0.388  0.414]


## 3. Introduction Hotelling Deflation

**Purpose: Update given matrix to calculate b-largest ||Eigenvector|| with Power Iteration.** <br>

**Hotelling Deflation Input:** (b-1)-th matrix computation, b-th Eigenvalue, b-th Eigenvector


In [11]:
def hotelling_deflation(matrix, val, vec):
    #convert eigenvector to transposable matrix-format
    hd_vec = np.matrix(vec)
    
    xi = hd_vec / (np.square(np.linalg.norm(hd_vec, 2)))
    
    #vector is vertical by default so transpose has to switch from formula
    subtract_mat = val * np.transpose(hd_vec) * xi
    
    #formula ressource: http://macs.citadel.edu/chenm/344.dir/08.dir/lect4_2.pdf
    return np.array(matrix - subtract_mat)

## 4. Interaction between all three functions

### 4.1 Explicit computation steps

In [12]:
#first hotelling deflation call
matrix2 = hotelling_deflation(matrix, eig_val, eig_vec)

# second power iteration call
eig_vec = power_iteration(matrix2, 100)
# second rayleigh quotient call
eig_val = rayleigh_quotient(matrix2, eig_vec)

#results
print("Eigenvalue:\n" + str(np.round(eig_val, 3)))
print("Eigenvector:\n" + str(np.round(eig_vec, 3)))

Eigenvalue:
[  1.261   2.332 -84.277  -2.311]
Eigenvector:
[ 0.793  0.429 -0.012 -0.433]


In [13]:
#second hotelling deflation call
matrix3 = hotelling_deflation(matrix2, eig_val, eig_vec)

# third power iteration call
eig_vec = power_iteration(matrix3, 100)
# third rayleigh quotient call
eig_val = rayleigh_quotient(matrix3, eig_vec)

#results
print("Eigenvalue:\n" + str(np.round(eig_val, 3)))
print("Eigenvector:\n" + str(np.round(eig_vec, 3)))

Eigenvalue:
[1.244 2.521 2.334 8.964]
Eigenvector:
[0.804 0.397 0.428 0.112]


In [14]:
#third hotelling deflation call
matrix4 = hotelling_deflation(matrix3, eig_val, eig_vec)

# fourth power iteration call
eig_vec = power_iteration(matrix4, 100)
# fourth rayleigh quotient call
eig_val = rayleigh_quotient(matrix4, eig_vec)

#results
print("Eigenvalue:\n" + str(np.round(eig_val, 3)))
print("Eigenvector:\n" + str(np.round(eig_vec, 3)))

Eigenvalue:
[1.414 2.394 2.056 3.357]
Eigenvector:
[0.707 0.418 0.486 0.298]


### 4.2 Comparision of results with Numpy

In [15]:
# computation of Eigenvalues and Eigenvectors with numpy.linalg.eig
E_values, E_vector = np.linalg.eig(matrix)
print("\nEigenvalues :\n" + str(np.round(E_values, 3)))
print("\nEigenvector :\n" + str(np.round(E_vector,3)))


Eigenvalues :
[ 8.763 -3.675  3.389 -0.477]

Eigenvector :
[[ 0.2   -0.796 -0.541 -0.186]
 [-0.799 -0.428  0.206  0.369]
 [-0.388  0.013  0.15  -0.909]
 [-0.414  0.429 -0.802  0.05 ]]


**Result: |λ1|> |λ2|> ...> |λn|, with corresponding Eigenvectors**